
import java.io.File;

/**
 *
 * @author Nicholas Pigni
 */
public class EditingPagePanel extends javax.swing.JPanel {

    /**
     * Il file del salvataggio dei punti di taglio del progetto corrente.
     */
    private File currentFile = null;

    /**
     * Creates new form EditingPagePanel
     */
    public EditingPagePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addRemoveRadioButtons = new javax.swing.ButtonGroup();
        leftMenu = new javax.swing.JPanel();
        undoButton = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();
        openButton = new javax.swing.JButton();
        addRadioButton = new javax.swing.JRadioButton();
        removeRadioButton = new javax.swing.JRadioButton();
        previewButton = new javax.swing.JCheckBox();
        saveButton = new javax.swing.JButton();
        saveAsButton = new javax.swing.JButton();
        currentFileName = new javax.swing.JLabel();
        dragRadioButton = new javax.swing.JRadioButton();
        curvedRadioButton1 = new javax.swing.JRadioButton();
        trianglePanel = new TrianglePanel();

        setMinimumSize(new java.awt.Dimension(1024, 768));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(1024, 768));
        setLayout(new java.awt.BorderLayout());

        undoButton.setText("Undo");
        undoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                undoButtonActionPerformed(evt);
            }
        });

        resetButton.setText("Reset");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });

        openButton.setText("Open");
        openButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openButtonActionPerformed(evt);
            }
        });

        addRemoveRadioButtons.add(addRadioButton);
        addRadioButton.setSelected(true);
        addRadioButton.setText("Add");
        addRadioButton.setToolTipText("");
        addRadioButton.setAlignmentY(0.0F);
        addRadioButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addRadioButtonActionPerformed(evt);
            }
        });

        addRemoveRadioButtons.add(removeRadioButton);
        removeRadioButton.setText("Remove");
        removeRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeRadioButtonActionPerformed(evt);
            }
        });

        previewButton.setText("Preview");
        previewButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        previewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previewButtonActionPerformed(evt);
            }
        });

        saveButton.setText("Save Dots");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        saveAsButton.setText("Save Dots As");
        saveAsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveAsButtonActionPerformed(evt);
            }
        });

        currentFileName.setText("No File Selected");

        addRemoveRadioButtons.add(dragRadioButton);
        dragRadioButton.setText("Drag");
        dragRadioButton.setToolTipText("");
        dragRadioButton.setAlignmentY(0.0F);
        dragRadioButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dragRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dragRadioButtonActionPerformed(evt);
            }
        });

        addRemoveRadioButtons.add(curvedRadioButton1);
        curvedRadioButton1.setText("Curved Line");
        curvedRadioButton1.setToolTipText("");
        curvedRadioButton1.setAlignmentY(0.0F);
        curvedRadioButton1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        curvedRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                curvedRadioButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout leftMenuLayout = new javax.swing.GroupLayout(leftMenu);
        leftMenu.setLayout(leftMenuLayout);
        leftMenuLayout.setHorizontalGroup(
            leftMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(leftMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(currentFileName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(resetButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(saveAsButton, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                    .addComponent(saveButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(openButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(undoButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(leftMenuLayout.createSequentialGroup()
                        .addGroup(leftMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(curvedRadioButton1)
                            .addComponent(addRadioButton)
                            .addComponent(previewButton)
                            .addComponent(dragRadioButton)
                            .addComponent(removeRadioButton))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        leftMenuLayout.setVerticalGroup(
            leftMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftMenuLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(addRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(curvedRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(removeRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dragRadioButton)
                .addGap(12, 12, 12)
                .addComponent(undoButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resetButton)
                .addGap(10, 10, 10)
                .addComponent(previewButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(openButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(saveButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(saveAsButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(currentFileName)
                .addContainerGap(466, Short.MAX_VALUE))
        );

        add(leftMenu, java.awt.BorderLayout.WEST);

        trianglePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout trianglePanelLayout = new javax.swing.GroupLayout(trianglePanel);
        trianglePanel.setLayout(trianglePanelLayout);
        trianglePanelLayout.setHorizontalGroup(
            trianglePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1022, Short.MAX_VALUE)
        );
        trianglePanelLayout.setVerticalGroup(
            trianglePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 766, Short.MAX_VALUE)
        );

        add(trianglePanel, java.awt.BorderLayout.CENTER);
        trianglePanel.getAccessibleContext().setAccessibleDescription("");
    }// </editor-fold>//GEN-END:initComponents

    private void removeRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeRadioButtonActionPerformed
        trianglePanel.isAdd = false;
        trianglePanel.isDrag = false;
    }//GEN-LAST:event_removeRadioButtonActionPerformed

    private void addRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addRadioButtonActionPerformed
        trianglePanel.isAdd = true;
        trianglePanel.isDrag = false;
    }//GEN-LAST:event_addRadioButtonActionPerformed

    private void previewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previewButtonActionPerformed
        trianglePanel.fillPoly = !trianglePanel.fillPoly;
        trianglePanel.drawDots = !trianglePanel.drawDots;
        repaint();
    }//GEN-LAST:event_previewButtonActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        trianglePanel.reset();
        repaint();
    }//GEN-LAST:event_resetButtonActionPerformed

    private void undoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_undoButtonActionPerformed
        trianglePanel.undo();
        repaint();
    }//GEN-LAST:event_undoButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        trianglePanel.saveDots();
        if (trianglePanel.getCurrentFileName() != null) {
            this.currentFileName.setText("Working File: " + trianglePanel.currentFile.getName());
        }
    }//GEN-LAST:event_saveButtonActionPerformed

    private void openButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openButtonActionPerformed
        trianglePanel.openDots();
        if (trianglePanel.getCurrentFileName() != null) {
            this.currentFileName.setText("Working File: " + trianglePanel.currentFile.getName());
        }
    }//GEN-LAST:event_openButtonActionPerformed

    private void saveAsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveAsButtonActionPerformed
        trianglePanel.saveDotsAs();
        if (trianglePanel.getCurrentFileName() != null) {
            this.currentFileName.setText("Working File: " + trianglePanel.currentFile.getName());
        }
    }//GEN-LAST:event_saveAsButtonActionPerformed

    private void dragRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dragRadioButtonActionPerformed
        trianglePanel.isAdd = false;
        trianglePanel.isDrag = true;
    }//GEN-LAST:event_dragRadioButtonActionPerformed

    private void curvedRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_curvedRadioButton1ActionPerformed
        trianglePanel.isCurved = true;
        trianglePanel.isAdd = false;
        trianglePanel.isDrag = true;
    }//GEN-LAST:event_curvedRadioButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton addRadioButton;
    private javax.swing.ButtonGroup addRemoveRadioButtons;
    private javax.swing.JLabel currentFileName;
    private javax.swing.JRadioButton curvedRadioButton1;
    private javax.swing.JRadioButton dragRadioButton;
    private javax.swing.JPanel leftMenu;
    private javax.swing.JButton openButton;
    private javax.swing.JCheckBox previewButton;
    private javax.swing.JRadioButton removeRadioButton;
    private javax.swing.JButton resetButton;
    private javax.swing.JButton saveAsButton;
    private javax.swing.JButton saveButton;
    private TrianglePanel trianglePanel;
    private javax.swing.JButton undoButton;
    // End of variables declaration//GEN-END:variables
}
