

/**
 *
 * @author Nicholas Pigni
 */
public class EditingPagePanel extends javax.swing.JPanel {


    /**
     * Il triangolo modello.
     */
    private TriangleModel triangleModel = new TriangleModel();

    /**
     * Creates new form EditingPagePanel
     */
    public EditingPagePanel() {
        initComponents();
        this.triangleModel = this.trianglePanel.getTriangleModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addRemoveRadioButtons = new javax.swing.ButtonGroup();
        buttonGroup1 = new javax.swing.ButtonGroup();
        pngGroup = new javax.swing.ButtonGroup();
        leftMenu = new javax.swing.JPanel();
        undoButton = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();
        openButton = new javax.swing.JButton();
        addRadioButton = new javax.swing.JRadioButton();
        removeRadioButton = new javax.swing.JRadioButton();
        previewButton = new javax.swing.JCheckBox();
        saveButton = new javax.swing.JButton();
        saveAsButton = new javax.swing.JButton();
        currentFileName = new javax.swing.JLabel();
        dragRadioButton = new javax.swing.JRadioButton();
        curvedRadioButton1 = new javax.swing.JRadioButton();
        livePreview = new javax.swing.JCheckBox();
        trianglePanel = new TrianglePanel();
        bottomMenu = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        pngSaveButton = new javax.swing.JButton();
        png500 = new javax.swing.JRadioButton();
        png1000 = new javax.swing.JRadioButton();
        pngFileChooserButton = new javax.swing.JButton();
        pngFileSelected = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        generateButton = new javax.swing.JButton();
        svgSavePanel = new javax.swing.JPanel();
        svgSaveButton = new javax.swing.JButton();
        svgFileChooserButton = new javax.swing.JButton();
        svgFileSelected = new javax.swing.JLabel();
        livePreviewPanel = new LivePreviewPanel();
        topMenu = new javax.swing.JPanel();
        livePreviewLabel = new javax.swing.JLabel();
        triangleLabel = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(1024, 768));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(1024, 768));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        setLayout(new java.awt.BorderLayout());

        leftMenu.setMinimumSize(new java.awt.Dimension(150, 350));
        leftMenu.setPreferredSize(new java.awt.Dimension(150, 350));

        undoButton.setText("Undo");
        undoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                undoButtonActionPerformed(evt);
            }
        });

        resetButton.setText("Reset");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });

        openButton.setText("Open");
        openButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openButtonActionPerformed(evt);
            }
        });

        addRemoveRadioButtons.add(addRadioButton);
        addRadioButton.setSelected(true);
        addRadioButton.setText("Add");
        addRadioButton.setToolTipText("");
        addRadioButton.setAlignmentY(0.0F);
        addRadioButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addRadioButtonActionPerformed(evt);
            }
        });

        addRemoveRadioButtons.add(removeRadioButton);
        removeRadioButton.setText("Remove");
        removeRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeRadioButtonActionPerformed(evt);
            }
        });

        previewButton.setText("Preview");
        previewButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        previewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previewButtonActionPerformed(evt);
            }
        });

        saveButton.setText("Save Dots");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        saveAsButton.setText("Save Dots As");
        saveAsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveAsButtonActionPerformed(evt);
            }
        });

        currentFileName.setText("No File Selected");

        addRemoveRadioButtons.add(dragRadioButton);
        dragRadioButton.setText("Drag");
        dragRadioButton.setToolTipText("");
        dragRadioButton.setAlignmentY(0.0F);
        dragRadioButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dragRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dragRadioButtonActionPerformed(evt);
            }
        });

        addRemoveRadioButtons.add(curvedRadioButton1);
        curvedRadioButton1.setText("Curved Line");
        curvedRadioButton1.setToolTipText("");
        curvedRadioButton1.setAlignmentY(0.0F);
        curvedRadioButton1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        curvedRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                curvedRadioButton1ActionPerformed(evt);
            }
        });

        livePreview.setSelected(true);
        livePreview.setText("Live Preview");
        livePreview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                livePreviewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout leftMenuLayout = new javax.swing.GroupLayout(leftMenu);
        leftMenu.setLayout(leftMenuLayout);
        leftMenuLayout.setHorizontalGroup(
            leftMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(leftMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(currentFileName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(resetButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(saveAsButton, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                    .addComponent(saveButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(openButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(undoButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(leftMenuLayout.createSequentialGroup()
                        .addGroup(leftMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(previewButton)
                            .addComponent(curvedRadioButton1)
                            .addComponent(addRadioButton)
                            .addComponent(dragRadioButton)
                            .addComponent(removeRadioButton))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(livePreview, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        leftMenuLayout.setVerticalGroup(
            leftMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftMenuLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(addRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(curvedRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(removeRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dragRadioButton)
                .addGap(12, 12, 12)
                .addComponent(undoButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resetButton)
                .addGap(10, 10, 10)
                .addComponent(previewButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(livePreview)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(openButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(saveButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(saveAsButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(currentFileName)
                .addContainerGap(143, Short.MAX_VALUE))
        );

        add(leftMenu, java.awt.BorderLayout.WEST);

        trianglePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        trianglePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                trianglePanelMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout trianglePanelLayout = new javax.swing.GroupLayout(trianglePanel);
        trianglePanel.setLayout(trianglePanelLayout);
        trianglePanelLayout.setHorizontalGroup(
            trianglePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1022, Short.MAX_VALUE)
        );
        trianglePanelLayout.setVerticalGroup(
            trianglePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 766, Short.MAX_VALUE)
        );

        add(trianglePanel, java.awt.BorderLayout.CENTER);
        trianglePanel.getAccessibleContext().setAccessibleDescription("");

        bottomMenu.setPreferredSize(new java.awt.Dimension(0, 200));
        bottomMenu.setRequestFocusEnabled(false);

        jPanel1.setBackground(new java.awt.Color(255, 153, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 0));

        pngSaveButton.setBackground(new java.awt.Color(204, 255, 51));
        pngSaveButton.setFont(new java.awt.Font("Verdana", 0, 48)); // NOI18N
        pngSaveButton.setForeground(new java.awt.Color(153, 153, 0));
        pngSaveButton.setText("Save PNG");
        pngSaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pngSaveButtonActionPerformed(evt);
            }
        });

        pngGroup.add(png500);
        png500.setSelected(true);
        png500.setText("Png 500x500 pixels");
        png500.setOpaque(false);
        png500.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                png500ActionPerformed(evt);
            }
        });

        pngGroup.add(png1000);
        png1000.setText("Png 1000x1000 pixels");
        png1000.setOpaque(false);
        png1000.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                png1000ActionPerformed(evt);
            }
        });

        pngFileChooserButton.setText("File Chooser");
        pngFileChooserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pngFileChooserButtonActionPerformed(evt);
            }
        });

        pngFileSelected.setText("No File Selected");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(pngFileChooserButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pngFileSelected))
                    .addComponent(png1000)
                    .addComponent(png500)
                    .addComponent(pngSaveButton))
                .addGap(62, 62, 62))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(png500)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(png1000)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pngFileChooserButton)
                    .addComponent(pngFileSelected))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pngSaveButton)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(0, 204, 204));

        generateButton.setBackground(new java.awt.Color(204, 255, 51));
        generateButton.setFont(new java.awt.Font("Verdana", 0, 48)); // NOI18N
        generateButton.setForeground(new java.awt.Color(153, 153, 0));
        generateButton.setText("Generate");
        generateButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        generateButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        generateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(generateButton, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(generateButton, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                .addContainerGap())
        );

        svgSavePanel.setBackground(new java.awt.Color(255, 153, 0));
        svgSavePanel.setPreferredSize(new java.awt.Dimension(400, 0));

        svgSaveButton.setBackground(new java.awt.Color(204, 255, 51));
        svgSaveButton.setFont(new java.awt.Font("Verdana", 0, 48)); // NOI18N
        svgSaveButton.setForeground(new java.awt.Color(153, 153, 0));
        svgSaveButton.setText("Save SVG");
        svgSaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                svgSaveButtonActionPerformed(evt);
            }
        });

        svgFileChooserButton.setText("File Chooser");
        svgFileChooserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                svgFileChooserButtonActionPerformed(evt);
            }
        });

        svgFileSelected.setText("No File Selected");

        javax.swing.GroupLayout svgSavePanelLayout = new javax.swing.GroupLayout(svgSavePanel);
        svgSavePanel.setLayout(svgSavePanelLayout);
        svgSavePanelLayout.setHorizontalGroup(
            svgSavePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, svgSavePanelLayout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addGroup(svgSavePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(svgSavePanelLayout.createSequentialGroup()
                        .addComponent(svgFileChooserButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(svgFileSelected))
                    .addComponent(svgSaveButton))
                .addGap(62, 62, 62))
        );
        svgSavePanelLayout.setVerticalGroup(
            svgSavePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, svgSavePanelLayout.createSequentialGroup()
                .addContainerGap(74, Short.MAX_VALUE)
                .addGroup(svgSavePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(svgFileChooserButton)
                    .addComponent(svgFileSelected))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(svgSaveButton)
                .addContainerGap())
        );

        javax.swing.GroupLayout bottomMenuLayout = new javax.swing.GroupLayout(bottomMenu);
        bottomMenu.setLayout(bottomMenuLayout);
        bottomMenuLayout.setHorizontalGroup(
            bottomMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bottomMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(svgSavePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        bottomMenuLayout.setVerticalGroup(
            bottomMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bottomMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bottomMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(svgSavePanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))
                .addContainerGap())
        );

        add(bottomMenu, java.awt.BorderLayout.SOUTH);

        livePreviewPanel.setLivePreview(livePreview.isEnabled());

        javax.swing.GroupLayout livePreviewPanelLayout = new javax.swing.GroupLayout(livePreviewPanel);
        livePreviewPanel.setLayout(livePreviewPanelLayout);
        livePreviewPanelLayout.setHorizontalGroup(
            livePreviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        livePreviewPanelLayout.setVerticalGroup(
            livePreviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 468, Short.MAX_VALUE)
        );

        add(livePreviewPanel, java.awt.BorderLayout.EAST);

        livePreviewLabel.setFont(new java.awt.Font("Verdana Pro Cond Black", 0, 24)); // NOI18N
        livePreviewLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        livePreviewLabel.setText("Live Preview");

        triangleLabel.setFont(new java.awt.Font("Verdana Pro Cond Black", 0, 24)); // NOI18N
        triangleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        triangleLabel.setText("Triangle");
        triangleLabel.setDoubleBuffered(true);

        javax.swing.GroupLayout topMenuLayout = new javax.swing.GroupLayout(topMenu);
        topMenu.setLayout(topMenuLayout);
        topMenuLayout.setHorizontalGroup(
            topMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, topMenuLayout.createSequentialGroup()
                .addContainerGap(225, Short.MAX_VALUE)
                .addComponent(triangleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(livePreviewLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        topMenuLayout.setVerticalGroup(
            topMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, topMenuLayout.createSequentialGroup()
                .addContainerGap(66, Short.MAX_VALUE)
                .addGroup(topMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(livePreviewLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(triangleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        add(topMenu, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void removeRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeRadioButtonActionPerformed
        this.trianglePanel.isAdd = false;
        this.trianglePanel.isDrag = false;
    }//GEN-LAST:event_removeRadioButtonActionPerformed

    private void addRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addRadioButtonActionPerformed
        this.trianglePanel.isAdd = true;
        this.trianglePanel.isDrag = false;
    }//GEN-LAST:event_addRadioButtonActionPerformed

    private void previewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previewButtonActionPerformed
        this.trianglePanel.fillPoly = !this.trianglePanel.fillPoly;
        this.trianglePanel.drawDots = !this.trianglePanel.drawDots;
        repaint();
    }//GEN-LAST:event_previewButtonActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        this.trianglePanel.reset();
        this.livePreviewPanel.updateFromArea(this.trianglePanel.generate());
        repaint();
    }//GEN-LAST:event_resetButtonActionPerformed

    private void undoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_undoButtonActionPerformed
        this.trianglePanel.undo();
        this.livePreviewPanel.updateFromArea(this.trianglePanel.generate());
        repaint();
    }//GEN-LAST:event_undoButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        this.trianglePanel.saveDots();
        if (this.trianglePanel.getCurrentFileName() != null) {
            this.currentFileName.setText("Working File: " + this.trianglePanel.currentFile.getName());
        }
        this.livePreviewPanel.updateFromArea(this.trianglePanel.generate());
    }//GEN-LAST:event_saveButtonActionPerformed

    private void openButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openButtonActionPerformed
        this.trianglePanel.openDots();
        if (this.trianglePanel.getCurrentFileName() != null) {
            this.currentFileName.setText("Working File: " + this.trianglePanel.currentFile.getName());
        }
        this.livePreviewPanel.updateFromArea(this.trianglePanel.generate());

    }//GEN-LAST:event_openButtonActionPerformed

    private void saveAsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveAsButtonActionPerformed
        this.trianglePanel.saveDotsAs();
        if (this.trianglePanel.getCurrentFileName() != null) {
            this.currentFileName.setText("Working File: " + this.trianglePanel.currentFile.getName());
        }
        this.livePreviewPanel.updateFromArea(this.trianglePanel.generate());

    }//GEN-LAST:event_saveAsButtonActionPerformed

    private void dragRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dragRadioButtonActionPerformed
        this.trianglePanel.isAdd = false;
        this.trianglePanel.isDrag = true;
        this.trianglePanel.isCurved = false;
    }//GEN-LAST:event_dragRadioButtonActionPerformed

    private void curvedRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_curvedRadioButton1ActionPerformed
        this.trianglePanel.isCurved = true;
        this.trianglePanel.isAdd = false;
        this.trianglePanel.isDrag = true;
    }//GEN-LAST:event_curvedRadioButton1ActionPerformed

    private void livePreviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_livePreviewActionPerformed
        this.livePreviewPanel.setLivePreview(this.livePreview.isSelected());
        this.livePreviewPanel.updateFromArea(this.trianglePanel.generate());
    }//GEN-LAST:event_livePreviewActionPerformed

    private void trianglePanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_trianglePanelMouseReleased
        this.livePreviewPanel.repaint();
        this.livePreviewPanel.updateFromArea(this.trianglePanel.generate());
    }//GEN-LAST:event_trianglePanelMouseReleased

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        this.livePreviewPanel.repaint();
    }//GEN-LAST:event_formMouseClicked

    private void pngSaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pngSaveButtonActionPerformed
        this.livePreviewPanel.savePNG();
    }//GEN-LAST:event_pngSaveButtonActionPerformed

    private void pngFileChooserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pngFileChooserButtonActionPerformed
        if (this.livePreviewPanel.selectPngFile() != null) {
            this.pngFileSelected.setText("Working File: " + this.livePreviewPanel.currentPngFile.getName());
        }
    }//GEN-LAST:event_pngFileChooserButtonActionPerformed

    private void png500ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_png500ActionPerformed
        this.livePreviewPanel.isMinimumResolution = true;
    }//GEN-LAST:event_png500ActionPerformed

    private void png1000ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_png1000ActionPerformed
        this.livePreviewPanel.isMinimumResolution = false;
    }//GEN-LAST:event_png1000ActionPerformed

    private void svgSaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_svgSaveButtonActionPerformed
        this.livePreviewPanel.saveSVG();
    }//GEN-LAST:event_svgSaveButtonActionPerformed

    private void svgFileChooserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_svgFileChooserButtonActionPerformed
        if (this.livePreviewPanel.selectSvgFile() != null) {
            this.svgFileSelected.setText("Working File: " + this.livePreviewPanel.currentSvgFile.getName());
        }
    }//GEN-LAST:event_svgFileChooserButtonActionPerformed

    private void generateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateButtonActionPerformed
        this.livePreviewPanel.generate();
    }//GEN-LAST:event_generateButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton addRadioButton;
    private javax.swing.ButtonGroup addRemoveRadioButtons;
    private javax.swing.JPanel bottomMenu;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel currentFileName;
    private javax.swing.JRadioButton curvedRadioButton1;
    private javax.swing.JRadioButton dragRadioButton;
    private javax.swing.JButton generateButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel leftMenu;
    private javax.swing.JCheckBox livePreview;
    private javax.swing.JLabel livePreviewLabel;
    private LivePreviewPanel livePreviewPanel;
    private javax.swing.JButton openButton;
    private javax.swing.JRadioButton png1000;
    private javax.swing.JRadioButton png500;
    private javax.swing.JButton pngFileChooserButton;
    private javax.swing.JLabel pngFileSelected;
    private javax.swing.ButtonGroup pngGroup;
    private javax.swing.JButton pngSaveButton;
    private javax.swing.JCheckBox previewButton;
    private javax.swing.JRadioButton removeRadioButton;
    private javax.swing.JButton resetButton;
    private javax.swing.JButton saveAsButton;
    private javax.swing.JButton saveButton;
    private javax.swing.JButton svgFileChooserButton;
    private javax.swing.JLabel svgFileSelected;
    private javax.swing.JButton svgSaveButton;
    private javax.swing.JPanel svgSavePanel;
    private javax.swing.JPanel topMenu;
    private javax.swing.JLabel triangleLabel;
    private TrianglePanel trianglePanel;
    private javax.swing.JButton undoButton;
    // End of variables declaration//GEN-END:variables
}
